[profile.default]
solc_version = '0.8.20'
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum_goerli = "${ARBITRUM_GOERLI_RPC_URL}"